In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[-3.0653e-29,  4.5914e-41, -2.3938e-29],
        [ 4.5914e-41,  5.6052e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -3.0657e-29],
        [ 4.5914e-41, -2.3794e-29,  4.5914e-41],
        [ 1.1210e-44,  0.0000e+00,  0.0000e+00]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.2049, 0.2481, 0.7944],
        [0.4805, 0.1340, 0.1055],
        [0.9413, 0.3000, 0.3158],
        [0.0470, 0.8505, 0.5653],
        [0.7927, 0.8369, 0.4642]])


In [6]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2636,  1.1071, -1.1702],
        [ 0.2785, -2.1054, -1.2999],
        [ 1.0121,  0.6529,  0.4281],
        [ 0.0086,  1.2152,  0.5563],
        [-1.4949,  0.4384,  0.2292]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [18]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4])torch.Size([16])torch.Size([2, 8])
