In [1]:
import torch

In [2]:
x = torch.randn((5,4))

In [8]:
type(x.grad_fn)

NoneType

In [36]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [37]:
y = x + 2
y.requires_grad_(True)
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [11]:
y.grad_fn

In [20]:
z = y * y * 3
out = z.mean()

In [22]:
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [28]:
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([[ 9.4611e+04, -1.6418e+01],
        [ 1.3295e+00,  8.7118e+00]])
False
True


In [38]:
x = torch.ones(2,2, requires_grad=True)
print(x)

y = x + 2
y.requires_grad_(True)
print(y)

z = y * y * 3
out = z.mean()

out.backward()

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [41]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [42]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000: 
    y = y * 2

print(y)

tensor([-1430.8668,  -950.1855,  -100.2814], grad_fn=<MulBackward0>)


In [44]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [46]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
